[versions]
mail = "1.6.2"
gson="2.10.1"
kotlin = "1.9.21"
truth="1.1.5"

[libraries]
mail = { group = "com.sun.mail", name = "javax.mail", version.ref = "mail" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

[plugins]

[bundles]

